eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/ #eureka server服务注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #eureka server服务注册中心的地址
  instance:
    instance-id: eureka-server-provider-test #修改主机映射名称
    prefer-ip-address: true #访问路径可以显示ip地址
spring:
  application:
    name: eureka-server-provider #该微服务应用的名字
  datasource:
   #type: com.alibaba.durid.pool.DruidDataSource
   #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
info:
 app.name: springcloud
 company.name: www.jason.com
 build.artifactId: $project.artifactId$
 build.version: $project.version$
